# 基础信息
name: habo
description: Minimalistic habit tracker.

# 设置为"none"表示不将此应用发布到pub.dev包管理器
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# 应用程序的版本号，这里是2.1.0+1。版本号由三部分组成，主版本号.次版本号.补丁版本号，后面的+1是构建号
version: 2.1.0+1

environment:
  # Flutter SDK的版本范围
  sdk: ">=2.18.1 <4.0.0"

# 列出项目运行时所需的依赖库
dependencies:
  # 指定使用Flutter SDK
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  table_calendar: ^3.0.9
  awesome_dialog: ^3.1.0
  loader_overlay: ^3.0.0
  introduction_screen: ^3.1.11
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.12
  package_info_plus: ^4.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  path: ^1.8.3
  fl_chart: ^0.64.0
  just_audio: ^0.9.34
  just_audio_mpv: ^0.1.7
  flutter_file_dialog: ^3.0.2
  file_picker: ^6.1.1
  path_provider: ^2.1.0
  awesome_notifications: ^0.8.2
  timezone: ^0.9.2
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  flutter_localizations:
    sdk: flutter
  intl: any
  intl_utils: ^2.8.5

# 列出项目开发阶段所需的依赖库
dev_dependencies:
  # Flutter官方提供的测试框架
  flutter_test:
    sdk: flutter

  # 用于代码质量检查的lint工具
  flutter_lints: ^3.0.1

# For now mipmaps are used.
# 配置Flutter应用的图标
flutter_icons:
  # 安卓和ios图标
  image_path_android: "assets/images/icon.png"
  image_path_ios: "assets/images/ios_icon.jpg"
  # 安卓应用图标前景图和背景色
  adaptive_icon_foreground: "assets/images/android_foreground.png"
  adaptive_icon_background: "#FFFFFF"
  # Android最低SDK版本
  min_sdk_android: 21
  # 是否生成对应的图标
  android: true
  ios: true
  # 是否移除iOS图标的alpha通道
  remove_alpha_ios: true
  # 是否为macOS生成图标，以及图标的路径
  macos:
    generate: true
    image_path: "assets/images/macos_icon.png"

flutter:
  # 是否使用Material Design
  uses-material-design: true
  # 是否自动生成国际化相关的代码
  generate: true

  # 列出项目中使用的静态资源路径
  assets:
    - assets/
    - assets/images/
    - assets/images/onboard/
    - assets/sounds/
    - assets/google_fonts/

# 国际化配置，启用国际化支持
flutter_intl:
  enabled: true
